#!/bin/sh

if [ x$1 = x ]; then
    echo "usage: $0 <executable>" 1>&2
    exit 1
fi

TVS_DIR="`dirname "$0"`"
ODE_DIR="`cd "$TVS_DIR"; cd ../ode; pwd`"
EXECUTABLE="`basename "$1"`"

export DYLD_LIBRARY_PATH="$ODE_DIR/ode/src/.libs:$DYLD_LIBRARY_PATH"

"$TVS_DIR/$EXECUTABLE"

exit $?

